### ISSUE TITLE
Make sure that bazel-steward is able to open PRs that get their checks triggered

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/bazel-steward#119]
For context read: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

I'd suggest to experiment with the last workaround. We want the setup process to be least painful for the user. PAT and dedicated account for each repository owner is certainly poor UX.

**Comment by MarconZet** [comment]
> 3. Install the App on any repository where workflows will run requiring tokens.

This doesn't sound very UX friendly

**Comment by lukaszwawrzyk** [comment]
I have one more strategy with GH token + PAT to try out:
use GH_TOKEN to create a PR draft and then use PAT to undraft the PR.
If it will trigger the job, it could be most elegant as it would silently create a draft and easily undraft it in one step (no close and reopen).
