### ISSUE TITLE
Research potential users

### ISSUE THREAD

**Issue by lukaszwawrzyk** [VirtusLab/bazel-steward#24]
Research public github repositories that use bazel.
Write down:
* reposistory name/url
* used languages and rules
* if it uses any dependency update system
It should guide us in further implementation

**Comment by mikkoziel** [comment]
[Doc with infromation](https://docs.google.com/document/d/1El6x3PVkMjpHr_gV-FQh8vBl6LCF2vgDvlsQbxdCCQo/edit?usp=sharing)

**Comment by mikkoziel** [comment]
[Sheet version](https://docs.google.com/spreadsheets/d/1en2umBoQx_bjBFSRq4W-c_dLp709fYQfIq1Ak6ZysWE/edit?usp=sharing)
