### ISSUE TITLE
bazel steward silently hangs after pushing branch

### ISSUE THREAD

**Issue by dhalperi** [VirtusLab/bazel-steward#349]
E.g., https://github.com/batfish/batfish/actions/runs/7963060467/job/21737883505

Seems to create a branch proposing to update rules-python, then goes silent and eventually times out after 6 hours.

**Comment by dhalperi** [comment]
Branch here: https://github.com/batfish/batfish/tree/bazel-steward/rules_python/0.31.0

**Comment by lukaszwawrzyk** [comment]
Oh, my... I suspect this is due to the count of PRs in the repo and it gets stuck on querying them. We have tested on forks of various repos, but well, PRs are not forked so it didn't came out. I will optimize this part.

**Comment by lukaszwawrzyk** [comment]
@dhalperi Feel free to reopen, though I hope that the fix will work. Fetching 8000 PRs is a good candidate that can cause hang.

**Comment by dhalperi** [comment]
Cool, thanks. FWIW, I tried again and I got:
>HTTP 403: API rate limit exceeded for installation ID 12265224. If you reach out to GitHub Support for help, please include the request ID FC40:6389:EF754C:1DDD25D:65D4D793. (https://api.github.com/repos/VirtusLab/bazel-steward/releases/tags/latest)
but that may just be because it was in the middle  of a prior 6 hour run.
