### ISSUE TITLE
BazelSteward doesn't update rules strating Bazel 7.2.0

### ISSUE THREAD

**Issue by hb-man** [VirtusLab/bazel-steward#396]
If you .bazelversion has version 7.1.2 the output for rules looks like this:
```
[DefaultDispatcher-worker-1] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - bazel mod graph --depth=1
[main] INFO org.virtuslab.bazelsteward.bzlmod.BzlModDependencyKind - Repositories [https://bcr.bazel.build]
```

If you .bazelversion has version above (7.2.0 or 7.2.1 available at current time), it will look like this:
```
[DefaultDispatcher-worker-1] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - bazel mod graph --depth=1
[main] INFO org.virtuslab.bazelsteward.bzlmod.BzlModDependencyKind - Repositories []
```
followed by messages that no update for rules could be found.

To reproduce, just `git clone  https://github.com/JetBrains/bazel-bsp.git` and run `coursier launch org.virtuslab:bazel-steward:1.5.0 --main org.virtuslab.bazelsteward.app.Main -- --no-remote --analyze-only`
Than change .bazelversion to 7.2.0 and run again.
The first time it will show repositories and available update suggestion, and the second time it wont.

**Comment by hb-man** [comment]
Okay, I figured it out.
It's because of the format change for MODULE.bazel.lock file format.
They don't output "cmdRegistries" flag you use to get repository.
https://github.com/VirtusLab/bazel-steward/blob/c08ac308016b5bdc4ce9572b1272cc281f57467e/kinds/bzlmod/src/main/kotlin/org/virtuslab/bazelsteward/bzlmod/BzlModDataExtractor.kt#L38:L46

**Comment by lukaszwawrzyk** [comment]
Thanks for the fix!
